object Versions {

    const val coreKtx = "1.9.0"
    const val appCompat = "1.5.1"
    const val viewModelLifecycleKtx = "2.5.1"
    const val coroutines = "1.6.4"
    const val material = "1.7.0"
    const val composeRuntime = "1.4.0-alpha02"
    const val compose = "1.3.0"
    const val composePaging = "1.0.0-alpha17"
    const val composeShimmer = "1.0.2"
    const val landscapistGlide = "1.4.3"
    const val composeActivity = "1.6.1"
    const val composeNavigation = "2.6.0-alpha03"
    const val hiltNavigation = "1.0.0"
    const val hilt = "2.44"
    const val inject = "1"
    const val retrofit = "2.9.0"
    const val okHttp = "4.10.0"
    const val moshi = "1.12.0"
    const val moshiCodeGen = "1.13.0"
    const val json = "20180813"
    const val jUnit = "4.13.2"
    const val mockitoKotlin = "4.0.0"
    const val espresso = "3.4.0"
    const val espressoJUnit = "1.1.4"
}