package com.msd117.cryptocompose.presentation.detail.model

data class CoinDetail(
    val logo: String,
    val id: Int,
    val name: String,
    val symbol: String,
    val slug: String,
    val description: String,
    val notice: String,
    val dateAdded: String,
    val tags: List<String>,
    val category: String,
    val platform: CoinPlatform?,
    val website: List<String>,
    val technicalDoc: List<String>,
    val twitter: List<String>,
    val reddit: List<String>,
    val messageBoard: List<String>,
    val announcement: List<String>,
    val chat: List<String>,
    val explorer: List<String>,
    val sourceCode: List<String>,
    val subreddit: String,
    val tagNames: List<String>,
    val tagGroups: List<String>,
    val twitterUsername: String,
    val isHidden: Int,
    val dateLaunched: String?,
    val contractAddress: List<ContractAddress>,
    val selfReportedCirculatingSupply: String?,
    val selfReportedTags: List<String>?
)
